#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# The script displays: username, user id, and
#     Home directory path for the user
# - Using 'while' loop

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
